name: pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    #- name: Set up Python ${{ matrix.python-version }}
      #uses: actions/setup-python@v2
      #with:
        #python-version: ${{ matrix.python-versions }} 

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint

    - name: Run pylint
      # Opt out of fail-fast for linting
      shell: bash {0}
      run: |
        pylint xicam --errors-only

